dist: bionic
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - python runtests.py
