dist: xenial  # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
    - master
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - python runtests.py
