name: Run unit tests

on: [push, pull_request]

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        id: checkout-repo
        with:
          fetch-depth: 0
      - name: Install uv build tool
        uses: astral-sh/setup-uv@v7
      - name: Install packages
        run: uv tool install tox --with tox-uv
      - name: Tox tests
        run: tox -v
